services:
  # backend
  server:
    image: todo-back-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
    depends_on:
      - mongo
      - redis

  # frontend
  app:
    image: todo-front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    depends_on:
      - server

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./todo-frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
  redis_data:
