services:
  # backend
  server:
    image: bloglist-back-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/bloglist
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # frontend
  app:
    image: bloglist-back-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
  redis_data:
